FROM nginx:alpine

COPY . /usr/share/nginx/html

EXPOSE 80

# TO build the image, run:
# docker bulid -t mywebsite:1.0.0 -f docker/Dockerfile .
# TO run the container, use:
# docker run -d -p 8080:80 mywebsite:1.0.0
# Access the website at http://localhost:8080